[package]
description = "LZMA / LZMA2 / LZIP / XZ compression ported from 'tukaani xz for java'"
edition = "2021"
homepage = "https://github.com/hasenbanck/lzma-rust2/"
name = "lzma-rust2"
repository = "https://github.com/hasenbanck/lzma-rust2/"
rust-version = "1.82"
version = "0.15.0"
keywords = ["lzma", "lzip", "xz"]
categories = ["compression", "no-std"]
license = "Apache-2.0"
exclude = ["/tests/data"]

[features]
default = ["std", "encoder", "optimization", "lzip", "xz"]
std = []
optimization = []
encoder = []
xz = ["crc", "sha2"]
lzip = ["crc"]

[dependencies]
crc = { version = "3.3", optional = true }
sha2 = { version = "0.10", optional = true }

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }
liblzma = { version = "0.4", features = ["static"] }

[[example]]
name = "lzip_reader"
required-features = ["std", "lzip"]

[[example]]
name = "lzip_writer"
required-features = ["std", "encoder", "lzip"]

[[example]]
name = "lzma2_reader"
required-features = ["std"]

[[example]]
name = "lzma2_writer"
required-features = ["std", "encoder"]

[[example]]
name = "lzma_reader"
required-features = ["std"]

[[example]]
name = "lzma_writer"
required-features = ["std", "encoder"]

[[example]]
name = "xz_reader"
required-features = ["std", "xz"]

[[example]]
name = "xz_writer"
required-features = ["std", "encoder", "xz"]

[[bench]]
name = "comparison"
harness = false

[package.metadata.docs.rs]
all-features = true
